In [ ]:
import numpy as np

In [ ]:
np.ones((1,13))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.random((3,4))

array([[0.11845445, 0.5593627 , 0.5945129 , 0.32517086],
       [0.40464825, 0.90225769, 0.42654124, 0.77046448],
       [0.3593869 , 0.93330614, 0.97495216, 0.88852357]])

In [ ]:
# np.linespace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Array Attributes**

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1.ndim

1

In [ ]:
a2.ndim

2

In [ ]:
a3.ndim

3

In [ ]:
# shape
a1.shape

(10,)

In [ ]:
a2.shape

(3, 4)

In [ ]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size
a3.size

8

In [ ]:
# itemsize
a1.itemsize

8

In [ ]:
#dtype
print(a1.dtype)

int64


**Changing Datatype**

In [ ]:
#astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

**Array Operations**

In [ ]:
A1= np.arange(12).reshape(3,4)
A2 = np.arange(12,24).reshape(3,4)
A2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# Scaler operations
# arithmetic
print(A1 * 2)
print(A1+A2)
print(A1-A2)
print(A1/A2)
print(A1*A2)
print(A1**A2)
print(A1%A2)
print(A1//A2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[                   0                    1                16384
              14348907]
 [          4294967296         762939453125      101559956668416
     11398895185373143]
 [ 1152921504606846976 -1261475310744950487  1864712049423024128
   6839173302027254275]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
# relational
print(A2 > 10)
print(A2>20)


[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [False False False False]
 [False  True  True  True]]


In [ ]:
# vector operations
#arithmatic
A1+A2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

**Array Functions**

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[56., 11., 60.],
       [52., 77., 74.],
       [73., 82., 78.]])

In [ ]:
# max/min /sum/product
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

82.0
11.0
563.0
5113156273505280.0


In [ ]:
# in specific rew
print(np.max(a1,axis=0))
print(np.max(a1,axis=1))


[73. 82. 78.]
[60. 77. 82.]


In [ ]:
# mean/median/std/var
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

62.55555555555556
73.0
20.77450954688414
431.58024691358025


In [ ]:
print(np.mean(a1,axis=0))
print(np.mean(a1,axis=1 ))

[60.33333333 56.66666667 70.66666667]
[42.33333333 67.66666667 77.66666667]


In [ ]:
#trignometric
print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))

[[-0.521551   -0.99999021 -0.30481062]
 [ 0.98662759  0.99952016 -0.98514626]
 [-0.67677196  0.31322878  0.51397846]]
[[ 0.85322011  0.0044257  -0.95241298]
 [-0.16299078 -0.03097503  0.17171734]
 [-0.73619272  0.9496777  -0.85780309]]
[[  -0.61127369 -225.95084645    0.32004039]
 [  -6.05327238  -32.26857578   -5.73702254]
 [   0.9192864     0.32982641   -0.59918   ]]


In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents
print(np.log(a1))
print(np.exp(a1))
print(np.sqrt(a1))
print(np.power(a1,3))


[[4.02535169 2.39789527 4.09434456]
 [3.95124372 4.34380542 4.30406509]
 [4.29045944 4.40671925 4.35670883]]
[[2.09165950e+24 5.98741417e+04 1.14200739e+26]
 [3.83100800e+22 2.75851345e+33 1.37338298e+32]
 [5.05239363e+31 4.09399696e+35 7.49841700e+33]]
[[7.48331477 3.31662479 7.74596669]
 [7.21110255 8.77496439 8.60232527]
 [8.54400375 9.05538514 8.83176087]]
[[175616.   1331. 216000.]
 [140608. 456533. 405224.]
 [389017. 551368. 474552.]]


In [ ]:
# round/floor/cell
print(np.round(np.random.random((2,3))*100))
print(np.floor(np.random.random((2,3))*100))
print(np.ceil(np.random.random((2,3))*100))

[[44. 68. 81.]
 [59. 34. 12.]]
[[71. 84. 49.]
 [69. 95. 80.]]
[[67. 92. 50.]
 [76. 88. 23.]]


**Indexing and Slicing**

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# last and first number
print(a1[-1])
print(a1[0])

9
0


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,2]

np.int64(6)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
#print 5
a3[1,0,1]

np.int64(5)

In [ ]:
a3[0,1,0]

np.int64(2)

In [ ]:
a3[0,0,0]

np.int64(0)

**slicing**

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5]

array([2, 3, 4])

In [ ]:
a1[1:8:2]

array([1, 3, 5, 7])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
# get all angle element
a2[::2,::3]


array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,:3:]

array([4, 5, 6])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
#first array second row
a3[0,1,:]

array([3, 4, 5])

In [ ]:
# 2nd array 2nd column
a3[1,::,1]

array([10, 13, 16])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

**Iterating**

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


**Reshape**

In [ ]:
#reshap


In [ ]:
# transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
#ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [ ]:
#Stacking
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)


In [ ]:
#horizontal stack
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
#verticle stack
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

**Splitting**

In [ ]:
# horizontal spliting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
# vertical spliting
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]