# np.sort
Return a sorted copy of an array.

In [ ]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([40, 71, 90, 12, 79, 20, 10,  6, 24,  3, 50, 86, 28, 98, 23])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[90, 61, 76, 47],
       [57, 97, 15, 40],
       [93, 68, 37,  5],
       [40, 93, 26, 90],
       [42, 45, 30, 76],
       [88, 65,  5, 18]])

In [ ]:
np.sort(a)

array([ 3,  6, 10, 12, 20, 23, 24, 28, 40, 50, 71, 79, 86, 90, 98])

In [ ]:
# row wise sorting by default axis = 1
np.sort(b)

array([[47, 61, 76, 90],
       [15, 40, 57, 97],
       [ 5, 37, 68, 93],
       [26, 40, 90, 93],
       [30, 42, 45, 76],
       [ 5, 18, 65, 88]])

In [ ]:
# column wise sorting
np.sort(b,axis=0)

array([[40, 45,  5,  5],
       [42, 61, 15, 18],
       [57, 65, 26, 40],
       [88, 68, 30, 47],
       [90, 93, 37, 76],
       [93, 97, 76, 90]])

In [ ]:
# sort desending orders
np.sort(a)[::-1]

array([98, 90, 86, 79, 71, 50, 40, 28, 24, 23, 20, 12, 10,  6,  3])

# np.append
The numpy.append() appends values along the mentioned axis at the end of the array

In [ ]:
a

array([40, 71, 90, 12, 79, 20, 10,  6, 24,  3, 50, 86, 28, 98, 23])

In [ ]:
np.append(a,200)

array([ 40,  71,  90,  12,  79,  20,  10,   6,  24,   3,  50,  86,  28,
        98,  23, 200])

In [ ]:
b

array([[90, 61, 76, 47],
       [57, 97, 15, 40],
       [93, 68, 37,  5],
       [40, 93, 26, 90],
       [42, 45, 30, 76],
       [88, 65,  5, 18]])

In [ ]:
np.append(b, np.ones((b.shape[0],1)), axis=1)

array([[90., 61., 76., 47.,  1.],
       [57., 97., 15., 40.,  1.],
       [93., 68., 37.,  5.,  1.],
       [40., 93., 26., 90.,  1.],
       [42., 45., 30., 76.,  1.],
       [88., 65.,  5., 18.,  1.]])

# np.concatenate
numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [ ]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique
With the help of np.unique() method, we can get the unique value from an array given as parameter in np.unique() method.

In [ ]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
e

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# np.expand_dims
with the help of numpy.expand_dims() method, we can get ethe expanded diensions of an array.

In [ ]:
a

array([40, 71, 90, 12, 79, 20, 10,  6, 24,  3, 50, 86, 28, 98, 23])

In [ ]:
np.expand_dims(a, axis=0)

array([[40, 71, 90, 12, 79, 20, 10,  6, 24,  3, 50, 86, 28, 98, 23]])

In [ ]:
np.expand_dims(a, axis=0).shape

(1, 15)

In [ ]:
np.expand_dims(a, axis=1)

array([[40],
       [71],
       [90],
       [12],
       [79],
       [20],
       [10],
       [ 6],
       [24],
       [ 3],
       [50],
       [86],
       [28],
       [98],
       [23]])

In [ ]:
np.expand_dims(a, axis=1).shape

(15, 1)

# np.where
The numpy.where() function return the indices of elements in an input array where the given condition is satisfied.

In [ ]:
a

array([40, 71, 90, 12, 79, 20, 10,  6, 24,  3, 50, 86, 28, 98, 23])

In [ ]:
# find the all indices with value grater than 50
np.where(a>50)

(array([ 1,  2,  4, 11, 13]),)

In [ ]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([40,  0,  0, 12,  0, 20, 10,  6, 24,  3, 50,  0, 28,  0, 23])

In [ ]:
# replace even number with 0
np.where(a%2==0,0,a)

array([ 0, 71,  0,  0, 79,  0,  0,  0,  0,  3,  0,  0,  0,  0, 23])

# np.argmax
The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [ ]:
a

array([40, 71, 90, 12, 79, 20, 10,  6, 24,  3, 50, 86, 28, 98, 23])

In [ ]:
np.argmax(a)

np.int64(13)

In [ ]:
b

array([[90, 61, 76, 47],
       [57, 97, 15, 40],
       [93, 68, 37,  5],
       [40, 93, 26, 90],
       [42, 45, 30, 76],
       [88, 65,  5, 18]])

In [ ]:
np.argmax(b,axis = 0)

array([2, 1, 0, 3])

In [ ]:
# row wise
np.argmax(b, axis = 1)

array([0, 1, 0, 1, 3, 0])

In [ ]:
# minimum value
np.argmin(b)

np.int64(11)

# np.cumsum
numpy.cumsum() function used when we want to compute the cumulative sum of array elements over a given axis.

In [ ]:
a

array([40, 71, 90, 12, 79, 20, 10,  6, 24,  3, 50, 86, 28, 98, 23])

In [ ]:
np.cumsum(a)

array([ 40, 111, 201, 213, 292, 312, 322, 328, 352, 355, 405, 491, 519,
       617, 640])

In [ ]:
b

array([[90, 61, 76, 47],
       [57, 97, 15, 40],
       [93, 68, 37,  5],
       [40, 93, 26, 90],
       [42, 45, 30, 76],
       [88, 65,  5, 18]])

In [ ]:
np.cumsum(b)

array([  90,  151,  227,  274,  331,  428,  443,  483,  576,  644,  681,
        686,  726,  819,  845,  935,  977, 1022, 1052, 1128, 1216, 1281,
       1286, 1304])

In [ ]:
np.cumsum(b,axis = 0)

array([[ 90,  61,  76,  47],
       [147, 158,  91,  87],
       [240, 226, 128,  92],
       [280, 319, 154, 182],
       [322, 364, 184, 258],
       [410, 429, 189, 276]])

In [ ]:
np.cumsum(b,axis = 1)

array([[ 90, 151, 227, 274],
       [ 57, 154, 169, 209],
       [ 93, 161, 198, 203],
       [ 40, 133, 159, 249],
       [ 42,  87, 117, 193],
       [ 88, 153, 158, 176]])

In [ ]:
a

array([40, 71, 90, 12, 79, 20, 10,  6, 24,  3, 50, 86, 28, 98, 23])

In [ ]:
np.cumprod(a)

array([                 40,                2840,              255600,
                   3067200,           242308800,          4846176000,
               48461760000,        290770560000,       6978493440000,
            20935480320000,    1046774016000000,   90022565376000000,
       2520631830528000000, 7214246433519828992,  -93028692429897728])

# np.percentile

In [ ]:
a

array([40, 71, 90, 12, 79, 20, 10,  6, 24,  3, 50, 86, 28, 98, 23])

In [ ]:
np.percentile(a,100)

np.float64(98.0)

In [ ]:
np.percentile(a,0)

np.float64(3.0)

In [ ]:
np.percentile(a,50)

np.float64(28.0)

In [ ]:
np.median(a)

np.float64(28.0)

# np.histogram

In [ ]:
a

array([40, 71, 90, 12, 79, 20, 10,  6, 24,  3, 50, 86, 28, 98, 23])

In [ ]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([2, 2, 4, 0, 1, 1, 0, 2, 1, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

**np.corrcoef**

In [ ]:
salary=np.array([20000,40000,25000,35000,60000])
experience=np.array([1,3,2,4,2])

In [ ]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

**np.isin**

In [ ]:
a

array([40, 71, 90, 12, 79, 20, 10,  6, 24,  3, 50, 86, 28, 98, 23])

In [ ]:
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a,items)

array([ True, False,  True, False, False,  True,  True, False, False,
       False,  True, False, False, False, False])

In [ ]:
a[np.isin(a,items)]

array([40, 90, 20, 10, 50])

**np.flip**

In [ ]:
a

array([40, 71, 90, 12, 79, 20, 10,  6, 24,  3, 50, 86, 28, 98, 23])

In [ ]:
np.flip(a)

array([23, 98, 28, 86, 50,  3, 24,  6, 10, 20, 79, 12, 90, 71, 40])

In [ ]:
b

array([[90, 61, 76, 47],
       [57, 97, 15, 40],
       [93, 68, 37,  5],
       [40, 93, 26, 90],
       [42, 45, 30, 76],
       [88, 65,  5, 18]])

In [ ]:
np.flip(b)

array([[18,  5, 65, 88],
       [76, 30, 45, 42],
       [90, 26, 93, 40],
       [ 5, 37, 68, 93],
       [40, 15, 97, 57],
       [47, 76, 61, 90]])

In [ ]:
np.flip(b,axis = 0)

array([[88, 65,  5, 18],
       [42, 45, 30, 76],
       [40, 93, 26, 90],
       [93, 68, 37,  5],
       [57, 97, 15, 40],
       [90, 61, 76, 47]])

**np.put**

In [ ]:
a

array([40, 71, 90, 12, 79, 20, 10,  6, 24,  3, 50, 86, 28, 98, 23])

In [ ]:
np.put(a,[0,1],[110,530])

In [ ]:
a

array([110, 530,  90,  12,  79,  20,  10,   6,  24,   3,  50,  86,  28,
        98,  23])

**np.delete**

In [ ]:
a

array([110, 530,  90,  12,  79,  20,  10,   6,  24,   3,  50,  86,  28,
        98,  23])

In [ ]:
np.delete(a,0)

array([530,  90,  12,  79,  20,  10,   6,  24,   3,  50,  86,  28,  98,
        23])

In [ ]:
np.delete(a,(0,2,4))

array([530,  12,  20,  10,   6,  24,   3,  50,  86,  28,  98,  23])



*   **Set functions**
*   np.union 1d
*   np.intersect1d
*   np.setdiff1d
*   np.setxor1d
*   np.in1d






In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [ ]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(m,n)

array([1, 2])

In [ ]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
np.in1d(m,n)

/tmp/ipython-input-207282267.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,n)


array([False, False,  True,  True,  True])

In [ ]:
m[np.in1d(m,1)]

/tmp/ipython-input-524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])